/*
** Copyright (c) 2001 PIXAR.  All rights reserved.  This program or
** documentation contains proprietary confidential information and trade
** secrets of PIXAR.  Reverse engineering of object code is prohibited.
** Use of copyright notice is precautionary and does not imply
** publication.
**
**                      RESTRICTED RIGHTS NOTICE
**
** Use, duplication, or disclosure by the Government is subject to the
** following restrictions:  For civilian agencies, subparagraphs (a) through
** (d) of the Commercial Computer Software--Restricted Rights clause at
** 52.227-19 of the FAR; and, for units of the Department of Defense, DoD
** Supplement to the FAR, clause 52.227-7013 (c)(1)(ii), Rights in
** Technical Data and Computer Software.
**
** Pixar
** 1200 Park Ave
** Emeryville, CA 94608
**
** ----------------------------------------------------------------------------
*/
/* code generated by slim 6.0, RAT 6.0 (Mar 11 2004 04:21:00) */
/* for kidd@localhost at: Sat Mar 26 16:25:59 FLE Standard Time 2005 */

/* includes ---------------------------------*/

/* defines ----------------------------------*/
#define SLIM_TYPEID_surface 0
#define SLIM_TYPEID_displacement 1
#define SLIM_TYPEID_volume 2
#define SLIM_TYPEID_light 3
#define SLIM_VERSION 600
#define SLIM_SHADERTYPE surface
#define SLIM_SHADERTYPEID SLIM_TYPEID_surface
#define SLIM_INSTANCETYPE color
#define SLIM_INSTANCENAME Noise

/* shader body ------------------------------*/
SLIM_SHADERTYPE
SLIM_INSTANCENAME (
  string SurfacePoint_Space="";
  varying point __Pref=point(-1e10,-1e10,-1e10);
)
{

/* static functions ----------------------*/

		void pxslSurfacePoint (
		    uniform string coordsys;
		    uniform float frequency;
		    uniform float ignorePref;
		    output point Q; 
		    output vector dQu;
		    output vector dQv;
		) 
		{
		    extern point P, Ps;
		    extern vector dPdu, dPdv;
		    extern point __Pref;
		    extern float du, dv;
		    uniform string sys;

		    if(coordsys == "")
		    	sys = "shader";
		    else
		    	sys = coordsys;
#if SLIM_SHADERTYPEID == SLIM_TYPEID_light
		    if (ignorePref == 0 && 1 == surface("__Pref", Q))
		    {
			Q = frequency * transform(sys, Q);
		    }
		    else
		    {
		    	Q = frequency * transform(sys, Ps);
		    }
		    dQu = vector Du(Q)*du;
		    dQv = vector Dv(Q)*dv;
#else
		    if (xcomp(__Pref) == -1e10 || ignorePref != 0)
		    {
			Q = frequency * transform (sys, P);
		    	dQu = vtransform (sys, dPdu*du*frequency);
		    	dQv = vtransform (sys, dPdv*dv*frequency);
		    }
		    else 
		    {
			Q = frequency * transform (sys, __Pref);
			dQu = vector Du(Q)*du;
		        dQv = vector Dv(Q)*dv;
		    }
#endif
		}
	    

#include "pxslUtil.h"
    	void
	pxslCNoise( float frequency;
	    	    point p;
		    vector dpu;
		    vector dpv;
		    output color result;
		   )
	{
	    point pp = frequency * p;
	    vector dppu = frequency * dpu;
	    vector dppv = frequency * dpv;
	    result = pxslFilteredCNoise(pp, dppu, dppv);
	}
    

/* dynamic functions ------------------------*/

/* local variables --------------------------*/
  point tmp0;
  color tmp3;
  vector tmp1;
  vector tmp2;

/* main body --------------------------------*/
  pxslSurfacePoint ( /* SurfacePoint */
    SurfacePoint_Space, /* Space */
    1, /* Frequency */
    0, /* IgnorePref */
    tmp0, /* Q */ 
    tmp1, /* dQu */ 
    tmp2  /* dQv */ 
    );
  pxslCNoise ( /* Noise */
    10.9, /* frequency */
    tmp0, /* p */ 
    tmp1, /* dpu */ 
    tmp2, /* dpv */ 
    tmp3  /* result */ 
    );
  Ci = tmp3;
  Oi = color(1,1,1);
}

